[project]
name = "odoo-addons-oca-l10n-paraguay"
version = "20.0.20261005.2"
dependencies = [
    "odoo-addon-l10n_py==20.0.*",
    "odoo-addon-l10n_py_account==20.0.*",
    "odoo-addon-l10n_py_base==20.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 20.0",
]
